import type { Metadata } from "next";

import { Sora } from "next/font/google";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./_components/app-sidebar";
import Providers from "@/lib/query/Providers";
import { Toaster } from "@/components/ui/toaster";
import { Suspense } from "react";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KGK | CMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <Providers>
          <Suspense>
            <SidebarProvider>
              <AppSidebar />
              <main className="w-full h-full">
                <SidebarTrigger />
                {children}
              </main>
              <Toaster />
            </SidebarProvider>
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
